[build]
  base = "/"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev:web"
  port = 8888
  targetPort = 5173
  autoLaunch = false
  publish = "dist"
  # This forces the internal server to bind specifically to IPv4
  host = "127.0.0.1"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/races"
  to = "/.netlify/functions/races"
  status = 200

[[redirects]]
  from = "/api/races/*"
  to = "/.netlify/functions/races"
  status = 200

[[redirects]]
  from = "/api/tracks"
  to = "/.netlify/functions/tracks"
  status = 200

[[redirects]]
  from = "/api/tracks/*"
  to = "/.netlify/functions/tracks"
  status = 200

[[redirects]]
  from = "/api/racers"
  to = "/.netlify/functions/racers"
  status = 200

[[redirects]]
  from = "/api/racers/*"
  to = "/.netlify/functions/racers"
  status = 200